# Generated by Django 2.2.24 on 2022-09-26 09:39

from django.db import migrations
import phonenumbers


def fill_owner_pure_phone_field(apps, shema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsed_phone_number):
            normalized_phone_number = phonenumbers.format_number(
                parsed_phone_number,
                phonenumbers.PhoneNumberFormat.E164
            )
            flat.owner_pure_phone = normalized_phone_number
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220926_1209'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone_field)
    ]
