# Generated by Django 2.2.24 on 2022-10-04 06:28

from django.db import migrations


def load_owners(apps, shema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            name=flat.owner,
            phone_number=flat.owners_phonenumber,
            pure_phone_number=flat.owner_pure_phone
        )
        owner.flats.add(flat)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_auto_20221004_0928'),
    ]

    operations = [
        migrations.RunPython(load_owners)
    ]
